// ignore: file_names
List<Map<String, dynamic>> subjectsMap = [
  {
    "Subject": "Introduction to computer science M",
    "Type": "P",
    "Level": "1",
    "for": ["Gm"],
    "Lecturer": "salim jamil alyazji",
    "Classroom": [
      "K203",
      "K204",
      "K216",
      "K403",
      "K316",
      "K217",
      "K303",
      "K304",
      "K317",
      "K404"
    ],
    "Duration": "3",
    "Capacity": 80,
    "Group": "101",
    "assigned_classroom": "K204",
    "assigned_time": [10, 42, 74]
  },
  {
    "Subject": "Introduction to computer science M",
    "Type": "P",
    "Level": "1",
    "for": ["Gm"],
    "Lecturer": "salim jamil alyazji",
    "Classroom": [
      "K203",
      "K204",
      "K216",
      "K403",
      "K316",
      "K217",
      "K303",
      "K304",
      "K317",
      "K404"
    ],
    "Duration": "3",
    "Capacity": 80,
    "Group": "102",
    "assigned_classroom": "K303",
    "assigned_time": [16, 48]
  },
  {
    "Subject": "Introduction to computer science F",
    "Type": "P",
    "Level": "1",
    "for": ["Gf"],
    "Lecturer": "salim jamil alyazji",
    "Classroom": [
      "K203",
      "K204",
      "K216",
      "K403",
      "K316",
      "K217",
      "K303",
      "K304",
      "K317",
      "K404"
    ],
    "Duration": "3",
    "Capacity": 80,
    "Group": "201",
    "assigned_classroom": "K203",
    "assigned_time": [4, 36, 68]
  },
  {
    "Subject": "Introduction to computer science F",
    "Type": "P",
    "Level": "1",
    "for": ["Gf"],
    "Lecturer": "salim jamil alyazji",
    "Classroom": [
      "K203",
      "K204",
      "K216",
      "K403",
      "K316",
      "K217",
      "K303",
      "K304",
      "K317",
      "K404"
    ],
    "Duration": "3",
    "Capacity": 80,
    "Group": "202",
    "assigned_classroom": "K304",
    "assigned_time": [19, 51]
  },
  {
    "Subject": "Introduction to computing M",
    "Type": "P",
    "Level": "1",
    "for": ["Gm"],
    "Lecturer": "Ehab Mahmoud Mortaja",
    "Classroom": [
      "K203",
      "K204",
      "K216",
      "K403",
      "K316",
      "K217",
      "K303",
      "K304",
      "K317",
      "K404"
    ],
    "Duration": "3",
    "Capacity": 80,
    "Group": "101",
    "assigned_classroom": "K204",
    "assigned_time": [9, 41, 73]
  },
  {
    "Subject": "Introduction to computing M",
    "Type": "P",
    "Level": "1",
    "for": ["Gm"],
    "Lecturer": "Ehab Mahmoud Mortaja",
    "Classroom": [
      "K203",
      "K204",
      "K216",
      "K403",
      "K316",
      "K217",
      "K303",
      "K304",
      "K317",
      "K404"
    ],
    "Duration": "3",
    "Capacity": 80,
    "Group": "102",
    "assigned_classroom": "K403",
    "assigned_time": [12, 44, 76]
  },
  {
    "Subject": "Introduction to computing F",
    "Type": "P",
    "Level": "1",
    "for": ["Gf"],
    "Lecturer": "Ehab Mahmoud Mortaja",
    "Classroom": ["L203", "L204", "L217", "L216", "L303", "L304"],
    "Duration": "3",
    "Capacity": 80,
    "Group": "201",
    "assigned_classroom": "L216",
    "assigned_time": [22, 54]
  },
  {
    "Subject": "Introduction to computing F",
    "Type": "P",
    "Level": "1",
    "for": ["Gf"],
    "Lecturer": "Ehab Mahmoud Mortaja",
    "Classroom": ["L203", "L204", "L217", "L216", "L303", "L304"],
    "Duration": "3",
    "Capacity": 80,
    "Group": "202",
    "assigned_classroom": "L304",
    "assigned_time": [20, 52]
  },
  {
    "Subject": "Programming (1) M",
    "Type": "P",
    "Level": "1",
    "for": ["Gm"],
    "Lecturer": "Iyad Mohamed Agha",
    "Classroom": [
      "K203",
      "K204",
      "K216",
      "K403",
      "K316",
      "K217",
      "K303",
      "K304",
      "K317",
      "K404"
    ],
    "Duration": "3",
    "Capacity": 80,
    "Group": "101",
    "assigned_classroom": "K204",
    "assigned_time": [28, 60]
  },
  {
    "Subject": "Programming (1) M",
    "Type": "P",
    "Level": "1",
    "for": ["Gm"],
    "Lecturer": "Khaled Mohamed Ismail",
    "Classroom": [
      "K203",
      "K204",
      "K216",
      "K403",
      "K316",
      "K217",
      "K303",
      "K304",
      "K317",
      "K404"
    ],
    "Duration": "3",
    "Capacity": 80,
    "Group": "102",
    "assigned_classroom": "K216",
    "assigned_time": [3, 35, 67]
  },
  {
    "Subject": "Programming (1) F",
    "Type": "P",
    "Level": "1",
    "for": ["Gf"],
    "Lecturer": "Iyad Hosni Shami",
    "Classroom": ["L203", "L204", "L217", "L216", "L303", "L304"],
    "Duration": "3",
    "Capacity": 80,
    "Group": "201",
    "assigned_classroom": "L304",
    "assigned_time": [2, 34, 66]
  },
  {
    "Subject": "Programming (1) F",
    "Type": "P",
    "Level": "1",
    "for": ["Gf"],
    "Lecturer": "Iyad Hosni Shami",
    "Classroom": ["L203", "L204", "L217", "L216", "L303", "L304"],
    "Duration": "3",
    "Capacity": 80,
    "Group": "202",
    "assigned_classroom": "L203",
    "assigned_time": [8, 40, 72]
  },
  {
    "Subject": "Discrete Mathematics M",
    "Type": "P",
    "Level": "1",
    "for": ["Gm"],
    "Lecturer": "Ayman Saqqa",
    "Classroom": [
      "K203",
      "K204",
      "K216",
      "K403",
      "K316",
      "K217",
      "K303",
      "K304",
      "K317",
      "K404"
    ],
    "Duration": "3",
    "Capacity": 80,
    "Group": "101",
    "assigned_classroom": "K317",
    "assigned_time": [24, 56]
  },
  {
    "Subject": "Discrete Mathematics M",
    "Type": "P",
    "Level": "1",
    "for": ["Gm"],
    "Lecturer": "Ashraf Abu Mughaiseeb",
    "Classroom": [
      "K203",
      "K204",
      "K216",
      "K403",
      "K316",
      "K217",
      "K303",
      "K304",
      "K317",
      "K404"
    ],
    "Duration": "3",
    "Capacity": 80,
    "Group": "102",
    "assigned_classroom": "K317",
    "assigned_time": [21, 53]
  },
  {
    "Subject": "Discrete mathematics for mobile computing M",
    "Type": "P",
    "Level": "1",
    "for": ["MO_1m"],
    "Lecturer": "Ashraf Abu Mughaiseeb",
    "Classroom": [
      "K203",
      "K204",
      "K216",
      "K403",
      "K316",
      "K217",
      "K303",
      "K304",
      "K317",
      "K404"
    ],
    "Duration": "3",
    "Capacity": 80,
    "Group": "101",
    "assigned_classroom": "K316",
    "assigned_time": [8, 40, 72]
  },
  {
    "Subject": "Discrete mathematics for mobile computing M",
    "Type": "P",
    "Level": "1",
    "for": ["MO_1m"],
    "Lecturer": "Ashraf Abu Mughaiseeb",
    "Classroom": [
      "K203",
      "K204",
      "K216",
      "K403",
      "K316",
      "K217",
      "K303",
      "K304",
      "K317",
      "K404"
    ],
    "Duration": "3",
    "Capacity": 80,
    "Group": "102",
    "assigned_classroom": "K216",
    "assigned_time": [8, 40, 72]
  },
  {
    "Subject": "Discrete mathematics for mobile computing F",
    "Type": "P",
    "Level": "1",
    "for": ["MO_1f"],
    "Lecturer": "Ashraf Abu Mughaiseeb",
    "Classroom": ["L203", "L204", "L217", "L216", "L303", "L304"],
    "Duration": "3",
    "Capacity": 80,
    "Group": "201",
    "assigned_classroom": "L304",
    "assigned_time": [12, 44, 76]
  },
  {
    "Subject": "Discrete mathematics for mobile computing F",
    "Type": "P",
    "Level": "1",
    "for": ["MO_1f"],
    "Lecturer": "Ashraf Abu Mughaiseeb",
    "Classroom": ["L203", "L204", "L217", "L216", "L303", "L304"],
    "Duration": "3",
    "Capacity": 80,
    "Group": "202",
    "assigned_classroom": "L204",
    "assigned_time": [14, 46, 78]
  },
  {
    "Subject": "Discrete mathematics F",
    "Type": "P",
    "Level": "1",
    "for": ["Gf"],
    "Lecturer": "Faten Abu Shawqa",
    "Classroom": ["L203", "L204", "L217", "L216", "L303", "L304"],
    "Duration": "3",
    "Capacity": 80,
    "Group": "201",
    "assigned_classroom": "L204",
    "assigned_time": [3, 35, 67]
  },
  {
    "Subject": "Discrete mathematics F",
    "Type": "P",
    "Level": "1",
    "for": ["Gf"],
    "Lecturer": "Faten Abu Shawqa",
    "Classroom": ["L203", "L204", "L217", "L216", "L303", "L304"],
    "Duration": "3",
    "Capacity": 80,
    "Group": "202",
    "assigned_classroom": "L204",
    "assigned_time": [28, 60]
  },
  {
    "Subject": "Data structures and algorithms M",
    "Type": "P",
    "Level": "2",
    "for": ["CS_2m", "SD_2m", "IT_2m"],
    "Lecturer": "Basem Omar Al-Ejla",
    "Classroom": [
      "K203",
      "K204",
      "K216",
      "K403",
      "K316",
      "K217",
      "K303",
      "K304",
      "K317",
      "K404"
    ],
    "Duration": "3",
    "Capacity": 80,
    "Group": "101",
    "assigned_classroom": "K317",
    "assigned_time": [19, 51]
  },
  {
    "Subject": "Data structures and algorithms M",
    "Type": "P",
    "Level": "2",
    "for": ["CS_2m", "SD_2m", "IT_2m"],
    "Lecturer": "Basem Omar Al-Ejla",
    "Classroom": [
      "K203",
      "K204",
      "K216",
      "K403",
      "K316",
      "K217",
      "K303",
      "K304",
      "K317",
      "K404"
    ],
    "Duration": "3",
    "Capacity": 80,
    "Group": "102",
    "assigned_classroom": "K316",
    "assigned_time": [13, 45, 77]
  },
  {
    "Subject": "Data structures and algorithms F",
    "Type": "P",
    "Level": "2",
    "for": ["CS_2f", "SD_2f", "IT_2f"],
    "Lecturer": "Basem Omar Al-Ejla",
    "Classroom": ["L203", "L204", "L217", "L216", "L303", "L304"],
    "Duration": "3",
    "Capacity": 80,
    "Group": "201",
    "assigned_classroom": "L204",
    "assigned_time": [2, 34, 66]
  },
  {
    "Subject": "Data structures and algorithms F",
    "Type": "P",
    "Level": "2",
    "for": ["CS_2f", "SD_2f", "IT_2f"],
    "Lecturer": "Basem Omar Al-Ejla",
    "Classroom": ["L203", "L204", "L217", "L216", "L303", "L304"],
    "Duration": "3",
    "Capacity": 80,
    "Group": "202",
    "assigned_classroom": "L304",
    "assigned_time": [16, 48]
  },
  {
    "Subject": "Programming language principles M",
    "Type": "P",
    "Level": "3",
    "for": ["CS_3m", "SD_3m", "IT_3m"],
    "Lecturer": "Salem Jamil Yaziji",
    "Classroom": [
      "I116",
      "I117",
      "I414",
      "I415",
      "I416",
      "I601",
      "I607",
      "I603"
    ],
    "Duration": "3",
    "Capacity": 80,
    "Group": "101",
    "assigned_classroom": "I415",
    "assigned_time": [14, 46, 78]
  },
  {
    "Subject": "Programming language principles M",
    "Type": "P",
    "Level": "3",
    "for": ["CS_3m", "SD_3m", "IT_3m"],
    "Lecturer": "Salem Jamil Yaziji",
    "Classroom": [
      "I116",
      "I117",
      "I414",
      "I415",
      "I416",
      "I601",
      "I607",
      "I603"
    ],
    "Duration": "3",
    "Capacity": 80,
    "Group": "102",
    "assigned_classroom": "I607",
    "assigned_time": [22, 54]
  },
  {
    "Subject": "Programming language principles F",
    "Type": "P",
    "Level": "3",
    "for": ["CS_3f", "SD_3f", "IT_3f"],
    "Lecturer": "Salem Jamil Yaziji",
    "Classroom": [
      "I101",
      "I107",
      "I102",
      "I602",
      "I607",
      "I208",
      "I202",
      "I207",
      "I201"
    ],
    "Duration": "3",
    "Capacity": 80,
    "Group": "201",
    "assigned_classroom": "I207",
    "assigned_time": [22, 54]
  },
  {
    "Subject": "Programming language principles F",
    "Type": "P",
    "Level": "3",
    "for": ["CS_3f", "SD_3f", "IT_3f"],
    "Lecturer": "Salem Jamil Yaziji",
    "Classroom": [
      "I101",
      "I107",
      "I102",
      "I602",
      "I607",
      "I208",
      "I202",
      "I207",
      "I201"
    ],
    "Duration": "3",
    "Capacity": 80,
    "Group": "202",
    "assigned_classroom": "I207",
    "assigned_time": [22, 54]
  },
  {
    "Subject": "Operating Systems M",
    "Type": "P",
    "Level": "3",
    "for": ["CS_3m", "SD_3m", "IT_3m"],
    "Lecturer": "Ehab Mahmoud Murtaja",
    "Classroom": [
      "K203",
      "K204",
      "K216",
      "K403",
      "K316",
      "K217",
      "K303",
      "K304",
      "K317",
      "K404"
    ],
    "Duration": "3",
    "Capacity": 80,
    "Group": "101",
    "assigned_classroom": "K303",
    "assigned_time": [25, 57]
  },
  {
    "Subject": "Operating Systems M",
    "Type": "P",
    "Level": "3",
    "for": ["CS_3m", "SD_3m", "IT_3m"],
    "Lecturer": "Ehab Mahmoud Murtaja",
    "Classroom": [
      "K203",
      "K204",
      "K216",
      "K403",
      "K316",
      "K217",
      "K303",
      "K304",
      "K317",
      "K404"
    ],
    "Duration": "3",
    "Capacity": 80,
    "Group": "102",
    "assigned_classroom": "K203",
    "assigned_time": [26, 58]
  },
  {
    "Subject": "Operating Systems F",
    "Type": "P",
    "Level": "3",
    "for": ["CS_3f", "SD_3f", "IT_3f"],
    "Lecturer": "Ehab Mahmoud Murtaja",
    "Classroom": ["L203", "L204", "L217", "L216", "L303", "L304"],
    "Duration": "3",
    "Capacity": 80,
    "Group": "201",
    "assigned_classroom": "L216",
    "assigned_time": [5, 37, 69]
  },
  {
    "Subject": "Operating Systems F",
    "Type": "P",
    "Level": "3",
    "for": ["CS_3f", "SD_3f", "IT_3f"],
    "Lecturer": "Ehab Mahmoud Murtaja",
    "Classroom": ["L203", "L204", "L217", "L216", "L303", "L304"],
    "Duration": "3",
    "Capacity": 80,
    "Group": "202",
    "assigned_classroom": "L303",
    "assigned_time": [14, 46, 78]
  },
  {
    "Subject": "Software Engineering M",
    "Type": "P",
    "Level": "2",
    "for": ["CS_2m", "SD_2m", "IT_2m"],
    "Lecturer": "Abdul Karim Mahmoud Al-Ashqar",
    "Classroom": [
      "I116",
      "I117",
      "I414",
      "I415",
      "I416",
      "I601",
      "I607",
      "I603"
    ],
    "Duration": "3",
    "Capacity": 80,
    "Group": "101",
    "assigned_classroom": "I416",
    "assigned_time": [1, 33, 65]
  },
  {
    "Subject": "Software Engineering M",
    "Type": "P",
    "Level": "2",
    "for": ["CS_2m", "SD_2m", "IT_2m"],
    "Lecturer": "Abdul Karim Mahmoud Al-Ashqar",
    "Classroom": [
      "I116",
      "I117",
      "I414",
      "I415",
      "I416",
      "I601",
      "I607",
      "I603"
    ],
    "Duration": "3",
    "Capacity": 80,
    "Group": "102",
    "assigned_classroom": "I601",
    "assigned_time": [1, 33, 65]
  },
  {
    "Subject": "Software Engineering F",
    "Type": "P",
    "Level": "2",
    "for": ["CS_2f", "SD_2f", "IT_2f"],
    "Lecturer": "Abdul Karim Mahmoud Al-Ashqar",
    "Classroom": [
      "I101",
      "I107",
      "I102",
      "I602",
      "I607",
      "I208",
      "I202",
      "I207",
      "I201"
    ],
    "Duration": "3",
    "Capacity": 80,
    "Group": "201",
    "assigned_classroom": "I602",
    "assigned_time": [29, 61]
  },
  {
    "Subject": "Software Engineering F",
    "Type": "P",
    "Level": "2",
    "for": ["CS_2f", "SD_2f", "IT_2f"],
    "Lecturer": "Abdul Karim Mahmoud Al-Ashqar",
    "Classroom": [
      "I101",
      "I107",
      "I102",
      "I602",
      "I607",
      "I208",
      "I202",
      "I207",
      "I201"
    ],
    "Duration": "3",
    "Capacity": 80,
    "Group": "202",
    "assigned_classroom": "I102",
    "assigned_time": [8, 40, 72]
  },
  {
    "Subject": "Database (1) M",
    "Type": "P",
    "Level": "2",
    "for": ["CS_2m", "SD_2m", "IT_2m"],
    "Lecturer": "Tawfiq Suleiman Barhoum",
    "Classroom": [
      "K203",
      "K204",
      "K216",
      "K403",
      "K316",
      "K217",
      "K303",
      "K304",
      "K317",
      "K404"
    ],
    "Duration": "3",
    "Capacity": 80,
    "Group": "101",
    "assigned_classroom": "K217",
    "assigned_time": [17, 49]
  },
  {
    "Subject": "Database (1) M",
    "Type": "P",
    "Level": "2",
    "for": ["CS_2m", "SD_2m", "IT_2m"],
    "Lecturer": "Tawfiq Suleiman Barhoum",
    "Classroom": [
      "K203",
      "K204",
      "K216",
      "K403",
      "K316",
      "K217",
      "K303",
      "K304",
      "K317",
      "K404"
    ],
    "Duration": "3",
    "Capacity": 80,
    "Group": "102",
    "assigned_classroom": "K317",
    "assigned_time": [6, 38, 70]
  },
  {
    "Subject": "Database (1) F",
    "Type": "P",
    "Level": "2",
    "for": ["CS_2f", "SD_2f", "IT_2f"],
    "Lecturer": "Tawfiq Suleiman Barhoum",
    "Classroom": ["L203", "L204", "L217", "L216", "L303", "L304"],
    "Duration": "3",
    "Capacity": 80,
    "Group": "201",
    "assigned_classroom": "L217",
    "assigned_time": [6, 38, 70]
  },
  {
    "Subject": "Database (1) F",
    "Type": "P",
    "Level": "2",
    "for": ["CS_2f", "SD_2f", "IT_2f"],
    "Lecturer": "Tawfiq Suleiman Barhoum",
    "Classroom": ["L203", "L204", "L217", "L216", "L303", "L304"],
    "Duration": "3",
    "Capacity": 80,
    "Group": "202",
    "assigned_classroom": "L303",
    "assigned_time": [11, 43, 75]
  },
  {
    "Subject": "Analysis and design of algorithms M",
    "Type": "P",
    "Level": "3",
    "for": ["CS_3m", "SD_3m", "IT_3m"],
    "Lecturer": "Basem Omar Al-Ejla",
    "Classroom": [
      "K203",
      "K204",
      "K216",
      "K403",
      "K316",
      "K217",
      "K303",
      "K304",
      "K317",
      "K404"
    ],
    "Duration": "3",
    "Capacity": 80,
    "Group": "101",
    "assigned_classroom": "K403",
    "assigned_time": [19, 51]
  },
  {
    "Subject": "Analysis and design of algorithms M",
    "Type": "P",
    "Level": "3",
    "for": ["CS_3m", "SD_3m", "IT_3m"],
    "Lecturer": "Basem Omar Al-Ejla",
    "Classroom": [
      "K203",
      "K204",
      "K216",
      "K403",
      "K316",
      "K217",
      "K303",
      "K304",
      "K317",
      "K404"
    ],
    "Duration": "3",
    "Capacity": 80,
    "Group": "102",
    "assigned_classroom": "K204",
    "assigned_time": [14, 46, 78]
  },
  {
    "Subject": "Analysis and design of algorithms F",
    "Type": "P",
    "Level": "3",
    "for": ["CS_3f", "SD_3f", "IT_3f"],
    "Lecturer": "Basem Omar Al-Ejla",
    "Classroom": ["L203", "L204", "L217", "L216", "L303", "L304"],
    "Duration": "3",
    "Capacity": 80,
    "Group": "201",
    "assigned_classroom": "L204",
    "assigned_time": [29, 61]
  },
  {
    "Subject": "Analysis and design of algorithms F",
    "Type": "P",
    "Level": "3",
    "for": ["CS_3f", "SD_3f", "IT_3f"],
    "Lecturer": "Basem Omar Al-Ejla",
    "Classroom": ["L203", "L204", "L217", "L216", "L303", "L304"],
    "Duration": "3",
    "Capacity": 80,
    "Group": "202",
    "assigned_classroom": "L303",
    "assigned_time": [18, 50]
  },
  {
    "Subject": "Graduation Research M",
    "Type": "P",
    "Level": "4",
    "for": ["CS_4m", "SD_4m", "IT_4m", "MM_4m", "MO_4m"],
    "Lecturer": "Khaled Mohamed Ismail",
    "Classroom": [
      "K203",
      "K204",
      "K216",
      "K403",
      "K316",
      "K217",
      "K303",
      "K304",
      "K317",
      "K404"
    ],
    "Duration": "1",
    "Capacity": 80,
    "Group": "101",
    "assigned_classroom": "K316",
    "assigned_time": 58
  },
  {
    "Subject": "Graduation Research M",
    "Type": "P",
    "Level": "4",
    "for": ["CS_4m", "SD_4m", "IT_4m", "MM_4m", "MO_4m"],
    "Lecturer": "Khaled Mohamed Ismail",
    "Classroom": [
      "K203",
      "K204",
      "K216",
      "K403",
      "K316",
      "K217",
      "K303",
      "K304",
      "K317",
      "K404"
    ],
    "Duration": "1",
    "Capacity": 80,
    "Group": "102",
    "assigned_classroom": "K316",
    "assigned_time": 7
  },
  {
    "Subject": "Graduation Research M",
    "Type": "P",
    "Level": "4",
    "for": ["CS_4m", "SD_4m", "IT_4m", "MM_4m", "MO_4m"],
    "Lecturer": "Khaled Mohamed Ismail",
    "Classroom": [
      "K203",
      "K204",
      "K216",
      "K403",
      "K316",
      "K217",
      "K303",
      "K304",
      "K317",
      "K404"
    ],
    "Duration": "1",
    "Capacity": 80,
    "Group": "103",
    "assigned_classroom": "K317",
    "assigned_time": 40
  },
  {
    "Subject": "Graduation Research F",
    "Type": "P",
    "Level": "4",
    "for": ["CS_4f", "SD_4f", "IT_4f", "MM_4f", "MO_4f"],
    "Lecturer": "Khaled Mohamed Ismail",
    "Classroom": ["L203", "L204", "L217", "L216", "L303", "L304"],
    "Duration": "1",
    "Capacity": 80,
    "Group": "201",
    "assigned_classroom": "L216",
    "assigned_time": 41
  },
  {
    "Subject": "Graduation Research F",
    "Type": "P",
    "Level": "4",
    "for": ["CS_4f", "SD_4f", "IT_4f", "MM_4f", "MO_4f"],
    "Lecturer": "Khaled Mohamed Ismail",
    "Classroom": ["L203", "L204", "L217", "L216", "L303", "L304"],
    "Duration": "1",
    "Capacity": 80,
    "Group": "202",
    "assigned_classroom": "L303",
    "assigned_time": 51
  },
  {
    "Subject": "Graduation Research F",
    "Type": "P",
    "Level": "4",
    "for": ["CS_4f", "SD_4f", "IT_4f", "MM_4f", "MO_4f"],
    "Lecturer": "Khaled Mohamed Ismail",
    "Classroom": ["L203", "L204", "L217", "L216", "L303", "L304"],
    "Duration": "1",
    "Capacity": 80,
    "Group": "201",
    "assigned_classroom": "I207",
    "assigned_time": [24, 56]
  },
  {
    "Subject": "Graduation Research F",
    "Type": "P",
    "Level": "4",
    "for": ["CS_4f", "SD_4f", "IT_4f", "MM_4f", "MO_4f"],
    "Lecturer": "Khaled Mohamed Ismail",
    "Classroom": ["L203", "L204", "L217", "L216", "L303", "L304"],
    "Duration": "1",
    "Capacity": 80,
    "Group": "201",
    "assigned_classroom": "I207",
    "assigned_time": [24, 56]
  },
  {
    "Subject": "Graduation Research F",
    "Type": "P",
    "Level": "4",
    "for": ["CS_4f", "SD_4f", "IT_4f", "MM_4f", "MO_4f"],
    "Lecturer": "Khaled Mohamed Ismail",
    "Classroom": ["L203", "L204", "L217", "L216", "L303", "L304"],
    "Duration": "1",
    "Capacity": 80,
    "Group": "201",
    "assigned_classroom": "I207",
    "assigned_time": [24, 56]
  },
  {
    "Subject": "Database management systems (1) M",
    "Type": "P",
    "Level": "2",
    "for": ["CS_2m", "SD_2m", "IT_2m"],
    "Lecturer": "Omar Emad Al-Ejla",
    "Classroom": [
      "I116",
      "I117",
      "I414",
      "I415",
      "I416",
      "I601",
      "I607",
      "I603"
    ],
    "Duration": "3",
    "Capacity": 80,
    "Group": "101",
    "assigned_classroom": "I601",
    "assigned_time": [3, 35, 67]
  },
  {
    "Subject": "Database management systems (1) M",
    "Type": "P",
    "Level": "2",
    "for": ["CS_2m", "SD_2m", "IT_2m"],
    "Lecturer": "Omar Emad Al-Ejla",
    "Classroom": [
      "I116",
      "I117",
      "I414",
      "I415",
      "I416",
      "I601",
      "I607",
      "I603"
    ],
    "Duration": "3",
    "Capacity": 80,
    "Group": "102",
    "assigned_classroom": "I607",
    "assigned_time": [12, 44, 76]
  },
  {
    "Subject": "Database management systems (1) F",
    "Type": "P",
    "Level": "2",
    "for": ["CS_2f", "SD_2f", "IT_2f"],
    "Lecturer": "Omar Emad Al-Ejla",
    "Classroom": [
      "I101",
      "I107",
      "I102",
      "I602",
      "I607",
      "I208",
      "I202",
      "I207",
      "I201"
    ],
    "Duration": "3",
    "Capacity": 80,
    "Group": "201",
    "assigned_classroom": "I101",
    "assigned_time": [2, 34, 66]
  },
  {
    "Subject": "Database management systems (1) F",
    "Type": "P",
    "Level": "2",
    "for": ["CS_2f", "SD_2f", "IT_2f"],
    "Lecturer": "Omar Emad Al-Ejla",
    "Classroom": [
      "I101",
      "I107",
      "I102",
      "I602",
      "I607",
      "I208",
      "I202",
      "I207",
      "I201"
    ],
    "Duration": "3",
    "Capacity": 80,
    "Group": "202",
    "assigned_classroom": "I107",
    "assigned_time": [5, 37, 69]
  },
  {
    "Subject": "Web Development and Programming (1) M",
    "Type": "P",
    "Level": "2",
    "for": ["CS_2m", "SD_2m", "IT_2m"],
    "Lecturer": "Thaer Al-Habbash",
    "Classroom": [
      "K203",
      "K204",
      "K216",
      "K403",
      "K316",
      "K217",
      "K303",
      "K304",
      "K317",
      "K404"
    ],
    "Duration": "3",
    "Capacity": 80,
    "Group": "101",
    "assigned_classroom": "K204",
    "assigned_time": [9, 41, 73]
  },
  {
    "Subject": "Web Development and Programming (1) M",
    "Type": "P",
    "Level": "2",
    "for": ["CS_2m", "SD_2m", "IT_2m"],
    "Lecturer": "Thaer Al-Habbash",
    "Classroom": [
      "K203",
      "K204",
      "K216",
      "K403",
      "K316",
      "K217",
      "K303",
      "K304",
      "K317",
      "K404"
    ],
    "Duration": "3",
    "Capacity": 80,
    "Group": "102",
    "assigned_classroom": "K217",
    "assigned_time": [21, 53]
  },
  {
    "Subject": "Web Development and Programming  (1) F",
    "Type": "P",
    "Level": "2",
    "for": ["CS_2f", "SD_2f", "IT_2f"],
    "Lecturer": "Thaer Al-Habbash",
    "Classroom": ["L203", "L204", "L217", "L216", "L303", "L304"],
    "Duration": "3",
    "Capacity": 80,
    "Group": "201",
    "assigned_classroom": "L204",
    "assigned_time": [4, 36, 68]
  },
  {
    "Subject": "Web Development and Programming  (1) F",
    "Type": "P",
    "Level": "2",
    "for": ["CS_2f", "SD_2f", "IT_2f"],
    "Lecturer": "Thaer Al-Habbash",
    "Classroom": ["L203", "L204", "L217", "L216", "L303", "L304"],
    "Duration": "3",
    "Capacity": 80,
    "Group": "202",
    "assigned_classroom": "L217",
    "assigned_time": [18, 50]
  },
  {
    "Subject": "Database management systems (2) M",
    "Type": "P",
    "Level": "3",
    "for": ["CS_3m", "SD_3m", "IT_3m"],
    "Lecturer": "Iyad Hosni Shami",
    "Classroom": [
      "K203",
      "K204",
      "K216",
      "K403",
      "K316",
      "K217",
      "K303",
      "K304",
      "K317",
      "K404"
    ],
    "Duration": "3",
    "Capacity": 80,
    "Group": "101",
    "assigned_classroom": "K404",
    "assigned_time": [22, 54]
  },
  {
    "Subject": "Database management systems (2) M",
    "Type": "P",
    "Level": "3",
    "for": ["CS_3m", "SD_3m", "IT_3m"],
    "Lecturer": "Iyad Hosni Shami",
    "Classroom": [
      "K203",
      "K204",
      "K216",
      "K403",
      "K316",
      "K217",
      "K303",
      "K304",
      "K317",
      "K404"
    ],
    "Duration": "3",
    "Capacity": 80,
    "Group": "102",
    "assigned_classroom": "K204",
    "assigned_time": [12, 44, 76]
  },
  {
    "Subject": "Database management systems (2) F",
    "Type": "P",
    "Level": "3",
    "for": ["CS_3f", "SD_3f", "IT_3f"],
    "Lecturer": "Iyad Hosni Shami",
    "Classroom": ["L203", "L204", "L217", "L216", "L303", "L304"],
    "Duration": "3",
    "Capacity": 80,
    "Group": "201",
    "assigned_classroom": "L303",
    "assigned_time": [14, 46, 78]
  },
  {
    "Subject": "Database management systems (2) F",
    "Type": "P",
    "Level": "3",
    "for": ["CS_3f", "SD_3f", "IT_3f"],
    "Lecturer": "Iyad Hosni Shami",
    "Classroom": ["L203", "L204", "L217", "L216", "L303", "L304"],
    "Duration": "3",
    "Capacity": 80,
    "Group": "202",
    "assigned_classroom": "L303",
    "assigned_time": [28, 60]
  },
  {
    "Subject": "Computer Security M",
    "Type": "P",
    "Level": "4",
    "for": ["CS_4m", "SD_4m"],
    "Lecturer": "Tawfiq Suleiman Barhoum",
    "Classroom": [
      "I116",
      "I117",
      "I414",
      "I415",
      "I416",
      "I601",
      "I607",
      "I603"
    ],
    "Duration": "3",
    "Capacity": 80,
    "Group": "101",
    "assigned_classroom": "I415",
    "assigned_time": [11, 43, 75]
  },
  {
    "Subject": "Computer Security F",
    "Type": "P",
    "Level": "4",
    "for": ["CS_4f", "SD_4f"],
    "Lecturer": "Tawfiq Suleiman Barhoum",
    "Classroom": [
      "I101",
      "I107",
      "I102",
      "I602",
      "I607",
      "I208",
      "I202",
      "I207",
      "I201"
    ],
    "Duration": "3",
    "Capacity": 80,
    "Group": "201",
    "assigned_classroom": "I107",
    "assigned_time": [18, 50]
  },
  {
    "Subject": "Computer Security F",
    "Type": "P",
    "Level": "4",
    "for": ["CS_4f", "SD_4f"],
    "Lecturer": "Tawfiq Suleiman Barhoum",
    "Classroom": [
      "I101",
      "I107",
      "I102",
      "I602",
      "I607",
      "I208",
      "I202",
      "I207",
      "I201"
    ],
    "Duration": "3",
    "Capacity": 80,
    "Group": "201",
    "assigned_classroom": "I107",
    "assigned_time": [18, 50]
  },
  {
    "Subject": "Computer Security F",
    "Type": "P",
    "Level": "4",
    "for": ["CS_4f", "SD_4f"],
    "Lecturer": "Tawfiq Suleiman Barhoum",
    "Classroom": [
      "I101",
      "I107",
      "I102",
      "I602",
      "I607",
      "I208",
      "I202",
      "I207",
      "I201"
    ],
    "Duration": "3",
    "Capacity": 80,
    "Group": "201",
    "assigned_classroom": "I107",
    "assigned_time": [18, 50]
  },
  {
    "Subject": "Computer Security F",
    "Type": "P",
    "Level": "4",
    "for": ["CS_4f", "SD_4f"],
    "Lecturer": "Tawfiq Suleiman Barhoum",
    "Classroom": [
      "I101",
      "I107",
      "I102",
      "I602",
      "I607",
      "I208",
      "I202",
      "I207",
      "I201"
    ],
    "Duration": "3",
    "Capacity": 80,
    "Group": "201",
    "assigned_classroom": "I107",
    "assigned_time": [18, 50]
  },
  {
    "Subject": "Computer Security F",
    "Type": "P",
    "Level": "4",
    "for": ["CS_4f", "SD_4f"],
    "Lecturer": "Tawfiq Suleiman Barhoum",
    "Classroom": [
      "I101",
      "I107",
      "I102",
      "I602",
      "I607",
      "I208",
      "I202",
      "I207",
      "I201"
    ],
    "Duration": "3",
    "Capacity": 80,
    "Group": "201",
    "assigned_classroom": "I107",
    "assigned_time": [18, 50]
  },
  {
    "Subject": "Software engineering principles M",
    "Type": "P",
    "Level": "2",
    "for": ["SD_2m", "IT_2m"],
    "Lecturer": "Khaled Mohamed Ismail",
    "Classroom": [
      "I116",
      "I117",
      "I414",
      "I415",
      "I416",
      "I601",
      "I607",
      "I603"
    ],
    "Duration": "3",
    "Capacity": 80,
    "Group": "101",
    "assigned_classroom": "I603",
    "assigned_time": [12, 44, 76]
  },
  {
    "Subject": "Software engineering principles M",
    "Type": "P",
    "Level": "2",
    "for": ["SD_2m", "IT_2m"],
    "Lecturer": "Khaled Mohamed Ismail",
    "Classroom": [
      "I116",
      "I117",
      "I414",
      "I415",
      "I416",
      "I601",
      "I607",
      "I603"
    ],
    "Duration": "3",
    "Capacity": 80,
    "Group": "102",
    "assigned_classroom": "I416",
    "assigned_time": [18, 50]
  },
  {
    "Subject": "Software engineering principles F",
    "Type": "P",
    "Level": "2",
    "for": ["SD_2f", "IT_2f"],
    "Lecturer": "Tamer Nazir Madi",
    "Classroom": ["L203", "L204", "L217", "L216", "L303", "L304"],
    "Duration": "3",
    "Capacity": 80,
    "Group": "201",
    "assigned_classroom": "L303",
    "assigned_time": [2, 34, 66]
  },
  {
    "Subject": "Software engineering principles F",
    "Type": "P",
    "Level": "2",
    "for": ["SD_2f", "IT_2f"],
    "Lecturer": "Tamer Nazir Madi",
    "Classroom": ["L203", "L204", "L217", "L216", "L303", "L304"],
    "Duration": "3",
    "Capacity": 80,
    "Group": "201",
    "assigned_classroom": "I202",
    "assigned_time": [1, 33, 65]
  },
  {
    "Subject": "Software engineering principles F",
    "Type": "P",
    "Level": "2",
    "for": ["SD_2f", "IT_2f"],
    "Lecturer": "Tamer Nazir Madi",
    "Classroom": ["L203", "L204", "L217", "L216", "L303", "L304"],
    "Duration": "3",
    "Capacity": 80,
    "Group": "201",
    "assigned_classroom": "I202",
    "assigned_time": [1, 33, 65]
  },
  {
    "Subject": "Software engineering principles F",
    "Type": "P",
    "Level": "2",
    "for": ["SD_2f", "IT_2f"],
    "Lecturer": "Tamer Nazir Madi",
    "Classroom": ["L203", "L204", "L217", "L216", "L303", "L304"],
    "Duration": "3",
    "Capacity": 80,
    "Group": "201",
    "assigned_classroom": "I202",
    "assigned_time": [1, 33, 65]
  },
  {
    "Subject": "Software engineering principles F",
    "Type": "P",
    "Level": "2",
    "for": ["SD_2f", "IT_2f"],
    "Lecturer": "Tamer Nazir Madi",
    "Classroom": ["L203", "L204", "L217", "L216", "L303", "L304"],
    "Duration": "3",
    "Capacity": 80,
    "Group": "201",
    "assigned_classroom": "I202",
    "assigned_time": [1, 33, 65]
  },
  {
    "Subject": "Software engineering principles F",
    "Type": "P",
    "Level": "2",
    "for": ["SD_2f", "IT_2f"],
    "Lecturer": "Tamer Nazir Madi",
    "Classroom": ["L203", "L204", "L217", "L216", "L303", "L304"],
    "Duration": "3",
    "Capacity": 80,
    "Group": "201",
    "assigned_classroom": "I202",
    "assigned_time": [1, 33, 65]
  },
  {
    "Subject": "Software engineering principles F",
    "Type": "P",
    "Level": "2",
    "for": ["SD_2f", "IT_2f"],
    "Lecturer": "Tamer Nazir Madi",
    "Classroom": ["L203", "L204", "L217", "L216", "L303", "L304"],
    "Duration": "3",
    "Capacity": 80,
    "Group": "201",
    "assigned_classroom": "I202",
    "assigned_time": [1, 33, 65]
  },
  {
    "Subject": "Software engineering principles F",
    "Type": "P",
    "Level": "2",
    "for": ["SD_2f", "IT_2f"],
    "Lecturer": "Tamer Nazir Madi",
    "Classroom": ["L203", "L204", "L217", "L216", "L303", "L304"],
    "Duration": "3",
    "Capacity": 80,
    "Group": "201",
    "assigned_classroom": "I202",
    "assigned_time": [1, 33, 65]
  },
  {
    "Subject": "Software engineering principles F",
    "Type": "P",
    "Level": "2",
    "for": ["SD_2f", "IT_2f"],
    "Lecturer": "Tamer Nazir Madi",
    "Classroom": ["L203", "L204", "L217", "L216", "L303", "L304"],
    "Duration": "3",
    "Capacity": 80,
    "Group": "201",
    "assigned_classroom": "I202",
    "assigned_time": [1, 33, 65]
  },
  {
    "Subject": "Software engineering principles F",
    "Type": "P",
    "Level": "2",
    "for": ["SD_2f", "IT_2f"],
    "Lecturer": "Tamer Nazir Madi",
    "Classroom": ["L203", "L204", "L217", "L216", "L303", "L304"],
    "Duration": "3",
    "Capacity": 80,
    "Group": "201",
    "assigned_classroom": "I202",
    "assigned_time": [1, 33, 65]
  },
  {
    "Subject": "Software engineering principles F",
    "Type": "P",
    "Level": "2",
    "for": ["SD_2f", "IT_2f"],
    "Lecturer": "Tamer Nazir Madi",
    "Classroom": ["L203", "L204", "L217", "L216", "L303", "L304"],
    "Duration": "3",
    "Capacity": 80,
    "Group": "201",
    "assigned_classroom": "I202",
    "assigned_time": [1, 33, 65]
  },
  {
    "Subject": "Software engineering principles F",
    "Type": "P",
    "Level": "2",
    "for": ["SD_2f", "IT_2f"],
    "Lecturer": "Tamer Nazir Madi",
    "Classroom": ["L203", "L204", "L217", "L216", "L303", "L304"],
    "Duration": "3",
    "Capacity": 80,
    "Group": "201",
    "assigned_classroom": "I202",
    "assigned_time": [1, 33, 65]
  },
  {
    "Subject": "Software engineering principles F",
    "Type": "P",
    "Level": "2",
    "for": ["SD_2f", "IT_2f"],
    "Lecturer": "Tamer Nazir Madi",
    "Classroom": ["L203", "L204", "L217", "L216", "L303", "L304"],
    "Duration": "3",
    "Capacity": 80,
    "Group": "201",
    "assigned_classroom": "I202",
    "assigned_time": [1, 33, 65]
  },
  {
    "Subject": "Software engineering principles F",
    "Type": "P",
    "Level": "2",
    "for": ["SD_2f", "IT_2f"],
    "Lecturer": "Tamer Nazir Madi",
    "Classroom": ["L203", "L204", "L217", "L216", "L303", "L304"],
    "Duration": "3",
    "Capacity": 80,
    "Group": "201",
    "assigned_classroom": "I202",
    "assigned_time": [1, 33, 65]
  },
  {
    "Subject": "Introduction to computers and the Internet M",
    "Type": "P",
    "Level": "1",
    "for": ["MM_1m"],
    "Lecturer": "Raed Saeed Rashid",
    "Classroom": [
      "K203",
      "K204",
      "K216",
      "K403",
      "K316",
      "K217",
      "K303",
      "K304",
      "K317",
      "K404"
    ],
    "Duration": "3",
    "Capacity": 80,
    "Group": "101",
    "assigned_classroom": "K317",
    "assigned_time": [0, 32, 64]
  },
  {
    "Subject": "Introduction to computers and the Internet F",
    "Type": "P",
    "Level": "1",
    "for": ["MM_1f"],
    "Lecturer": "Lamia Mohammed Al-Saeedi",
    "Classroom": ["L203", "L204", "L217", "L216", "L303", "L304"],
    "Duration": "3",
    "Capacity": 80,
    "Group": "201",
    "assigned_classroom": "L204",
    "assigned_time": [6, 38, 70]
  },
  {
    "Subject": "Media programing (1) M",
    "Type": "P",
    "Level": "1",
    "for": ["MM_1m"],
    "Lecturer": "Tamer Nazir Madi",
    "Classroom": [
      "K203",
      "K204",
      "K216",
      "K403",
      "K316",
      "K217",
      "K303",
      "K304",
      "K317",
      "K404"
    ],
    "Duration": "3",
    "Capacity": 80,
    "Group": "101",
    "assigned_classroom": "K316",
    "assigned_time": [21, 53]
  },
  {
    "Subject": "Media programing (1) F",
    "Type": "P",
    "Level": "1",
    "for": ["MM_1f"],
    "Lecturer": "Rawya Fawzy Awad Allah",
    "Classroom": ["L203", "L204", "L217", "L216", "L303", "L304"],
    "Duration": "3",
    "Capacity": 80,
    "Group": "201",
    "assigned_classroom": "L303",
    "assigned_time": [18, 50]
  },
  {
    "Subject": "Multimedia technology and its composition M",
    "Type": "P",
    "Level": "1",
    "for": ["MM_1m"],
    "Lecturer": "Ramy Othman Skaik",
    "Classroom": [
      "K203",
      "K204",
      "K216",
      "K403",
      "K316",
      "K217",
      "K303",
      "K304",
      "K317",
      "K404"
    ],
    "Duration": "3",
    "Capacity": 80,
    "Group": "101",
    "assigned_classroom": "K303",
    "assigned_time": [16, 48]
  },
  {
    "Subject": "Multimedia technology and its composition F",
    "Type": "P",
    "Level": "1",
    "for": ["MM_1f"],
    "Lecturer": "Lamia Mohammed Al-Saeedi",
    "Classroom": ["L203", "L204", "L217", "L216", "L303", "L304"],
    "Duration": "3",
    "Capacity": 80,
    "Group": "201",
    "assigned_classroom": "L216",
    "assigned_time": [7, 39, 71]
  },
  {
    "Subject": "Multimedia technology and its composition F",
    "Type": "P",
    "Level": "1",
    "for": ["MM_1f"],
    "Lecturer": "Lamia Mohammed Al-Saeedi",
    "Classroom": ["L203", "L204", "L217", "L216", "L303", "L304"],
    "Duration": "3",
    "Capacity": 80,
    "Group": "201",
    "assigned_classroom": "L216",
    "assigned_time": [7, 39, 71]
  },
  {
    "Subject": "Multimedia technology and its composition F",
    "Type": "P",
    "Level": "1",
    "for": ["MM_1f"],
    "Lecturer": "Lamia Mohammed Al-Saeedi",
    "Classroom": ["L203", "L204", "L217", "L216", "L303", "L304"],
    "Duration": "3",
    "Capacity": 80,
    "Group": "201",
    "assigned_classroom": "L216",
    "assigned_time": [7, 39, 71]
  },
  {
    "Subject": "Multimedia technology and its composition F",
    "Type": "P",
    "Level": "1",
    "for": ["MM_1f"],
    "Lecturer": "Lamia Mohammed Al-Saeedi",
    "Classroom": ["L203", "L204", "L217", "L216", "L303", "L304"],
    "Duration": "3",
    "Capacity": 80,
    "Group": "201",
    "assigned_classroom": "L216",
    "assigned_time": [7, 39, 71]
  },
  {
    "Subject": "Multimedia technology and its composition F",
    "Type": "P",
    "Level": "1",
    "for": ["MM_1f"],
    "Lecturer": "Lamia Mohammed Al-Saeedi",
    "Classroom": ["L203", "L204", "L217", "L216", "L303", "L304"],
    "Duration": "3",
    "Capacity": 80,
    "Group": "201",
    "assigned_classroom": "L216",
    "assigned_time": [7, 39, 71]
  },
  {
    "Subject": "Multimedia technology and its composition F",
    "Type": "P",
    "Level": "1",
    "for": ["MM_1f"],
    "Lecturer": "Lamia Mohammed Al-Saeedi",
    "Classroom": ["L203", "L204", "L217", "L216", "L303", "L304"],
    "Duration": "3",
    "Capacity": 80,
    "Group": "201",
    "assigned_classroom": "L216",
    "assigned_time": [7, 39, 71]
  },
  {
    "Subject": "Multimedia technology and its composition F",
    "Type": "P",
    "Level": "1",
    "for": ["MM_1f"],
    "Lecturer": "Lamia Mohammed Al-Saeedi",
    "Classroom": ["L203", "L204", "L217", "L216", "L303", "L304"],
    "Duration": "3",
    "Capacity": 80,
    "Group": "201",
    "assigned_classroom": "L216",
    "assigned_time": [7, 39, 71]
  },
  {
    "Subject": "Multimedia technology and its composition F",
    "Type": "P",
    "Level": "1",
    "for": ["MM_1f"],
    "Lecturer": "Lamia Mohammed Al-Saeedi",
    "Classroom": ["L203", "L204", "L217", "L216", "L303", "L304"],
    "Duration": "3",
    "Capacity": 80,
    "Group": "201",
    "assigned_classroom": "L216",
    "assigned_time": [7, 39, 71]
  },
  {
    "Subject": "Multimedia technology and its composition F",
    "Type": "P",
    "Level": "1",
    "for": ["MM_1f"],
    "Lecturer": "Lamia Mohammed Al-Saeedi",
    "Classroom": ["L203", "L204", "L217", "L216", "L303", "L304"],
    "Duration": "3",
    "Capacity": 80,
    "Group": "201",
    "assigned_classroom": "L216",
    "assigned_time": [7, 39, 71]
  },
  {
    "Subject": "Multimedia technology and its composition F",
    "Type": "P",
    "Level": "1",
    "for": ["MM_1f"],
    "Lecturer": "Lamia Mohammed Al-Saeedi",
    "Classroom": ["L203", "L204", "L217", "L216", "L303", "L304"],
    "Duration": "3",
    "Capacity": 80,
    "Group": "201",
    "assigned_classroom": "L216",
    "assigned_time": [7, 39, 71]
  },
  {
    "Subject": "Multimedia technology and its composition F",
    "Type": "P",
    "Level": "1",
    "for": ["MM_1f"],
    "Lecturer": "Lamia Mohammed Al-Saeedi",
    "Classroom": ["L203", "L204", "L217", "L216", "L303", "L304"],
    "Duration": "3",
    "Capacity": 80,
    "Group": "201",
    "assigned_classroom": "L216",
    "assigned_time": [7, 39, 71]
  },
  {
    "Subject": "Multimedia technology and its composition F",
    "Type": "P",
    "Level": "1",
    "for": ["MM_1f"],
    "Lecturer": "Lamia Mohammed Al-Saeedi",
    "Classroom": ["L203", "L204", "L217", "L216", "L303", "L304"],
    "Duration": "3",
    "Capacity": 80,
    "Group": "201",
    "assigned_classroom": "L216",
    "assigned_time": [7, 39, 71]
  },
  {
    "Subject": "Multimedia technology and its composition F",
    "Type": "P",
    "Level": "1",
    "for": ["MM_1f"],
    "Lecturer": "Lamia Mohammed Al-Saeedi",
    "Classroom": ["L203", "L204", "L217", "L216", "L303", "L304"],
    "Duration": "3",
    "Capacity": 80,
    "Group": "201",
    "assigned_classroom": "L216",
    "assigned_time": [7, 39, 71]
  },
  {
    "Subject": "Multimedia technology and its composition F",
    "Type": "P",
    "Level": "1",
    "for": ["MM_1f"],
    "Lecturer": "Lamia Mohammed Al-Saeedi",
    "Classroom": ["L203", "L204", "L217", "L216", "L303", "L304"],
    "Duration": "3",
    "Capacity": 80,
    "Group": "201",
    "assigned_classroom": "L216",
    "assigned_time": [7, 39, 71]
  },
  {
    "Subject": "Multimedia technology and its composition F",
    "Type": "P",
    "Level": "1",
    "for": ["MM_1f"],
    "Lecturer": "Lamia Mohammed Al-Saeedi",
    "Classroom": ["L203", "L204", "L217", "L216", "L303", "L304"],
    "Duration": "3",
    "Capacity": 80,
    "Group": "201",
    "assigned_classroom": "L216",
    "assigned_time": [7, 39, 71]
  },
  {
    "Subject": "Multimedia technology and its composition F",
    "Type": "P",
    "Level": "1",
    "for": ["MM_1f"],
    "Lecturer": "Lamia Mohammed Al-Saeedi",
    "Classroom": ["L203", "L204", "L217", "L216", "L303", "L304"],
    "Duration": "3",
    "Capacity": 80,
    "Group": "201",
    "assigned_classroom": "L216",
    "assigned_time": [7, 39, 71]
  },
  {
    "Subject": "Multimedia technology and its composition F",
    "Type": "P",
    "Level": "1",
    "for": ["MM_1f"],
    "Lecturer": "Lamia Mohammed Al-Saeedi",
    "Classroom": ["L203", "L204", "L217", "L216", "L303", "L304"],
    "Duration": "3",
    "Capacity": 80,
    "Group": "201",
    "assigned_classroom": "L216",
    "assigned_time": [7, 39, 71]
  },
  {
    "Subject": "Multimedia technology and its composition F",
    "Type": "P",
    "Level": "1",
    "for": ["MM_1f"],
    "Lecturer": "Lamia Mohammed Al-Saeedi",
    "Classroom": ["L203", "L204", "L217", "L216", "L303", "L304"],
    "Duration": "3",
    "Capacity": 80,
    "Group": "201",
    "assigned_classroom": "L216",
    "assigned_time": [7, 39, 71]
  },
  {
    "Subject": "Multimedia technology and its composition F",
    "Type": "P",
    "Level": "1",
    "for": ["MM_1f"],
    "Lecturer": "Lamia Mohammed Al-Saeedi",
    "Classroom": ["L203", "L204", "L217", "L216", "L303", "L304"],
    "Duration": "3",
    "Capacity": 80,
    "Group": "201",
    "assigned_classroom": "L216",
    "assigned_time": [7, 39, 71]
  },
  {
    "Subject": "Multimedia technology and its composition F",
    "Type": "P",
    "Level": "1",
    "for": ["MM_1f"],
    "Lecturer": "Lamia Mohammed Al-Saeedi",
    "Classroom": ["L203", "L204", "L217", "L216", "L303", "L304"],
    "Duration": "3",
    "Capacity": 80,
    "Group": "201",
    "assigned_classroom": "L216",
    "assigned_time": [7, 39, 71]
  },
  {
    "Subject": "Multimedia technology and its composition F",
    "Type": "P",
    "Level": "1",
    "for": ["MM_1f"],
    "Lecturer": "Lamia Mohammed Al-Saeedi",
    "Classroom": ["L203", "L204", "L217", "L216", "L303", "L304"],
    "Duration": "3",
    "Capacity": 80,
    "Group": "201",
    "assigned_classroom": "L216",
    "assigned_time": [7, 39, 71]
  },
  {
    "Subject": "Mobile Applications Programming (1) M",
    "Type": "P",
    "Level": "2",
    "for": ["MO_2m"],
    "Lecturer": "Hazem Awni Shehadeh Rikhawi",
    "Classroom": [
      "I116",
      "I117",
      "I414",
      "I415",
      "I416",
      "I601",
      "I607",
      "I603"
    ],
    "Duration": "3",
    "Capacity": 80,
    "Group": "101",
    "assigned_classroom": "I601",
    "assigned_time": [0, 32, 64]
  },
  {
    "Subject": "Mobile Applications Programming (1) F",
    "Type": "P",
    "Level": "2",
    "for": ["MO_2f"],
    "Lecturer": "Hazem Awni Shehadeh Rikhawi",
    "Classroom": [
      "I101",
      "I107",
      "I102",
      "I602",
      "I607",
      "I208",
      "I202",
      "I207",
      "I201"
    ],
    "Duration": "3",
    "Capacity": 80,
    "Group": "201",
    "assigned_classroom": "L204",
    "assigned_time": [24, 56]
  },
  {
    "Subject": "Mobile Applications Programming (1) F",
    "Type": "P",
    "Level": "2",
    "for": ["MO_2f"],
    "Lecturer": "Hazem Awni Shehadeh Rikhawi",
    "Classroom": [
      "I101",
      "I107",
      "I102",
      "I602",
      "I607",
      "I208",
      "I202",
      "I207",
      "I201"
    ],
    "Duration": "3",
    "Capacity": 80,
    "Group": "201",
    "assigned_classroom": "L204",
    "assigned_time": [24, 56]
  },
  {
    "Subject": "Mobile Applications Programming (1) F",
    "Type": "P",
    "Level": "2",
    "for": ["MO_2f"],
    "Lecturer": "Hazem Awni Shehadeh Rikhawi",
    "Classroom": [
      "I101",
      "I107",
      "I102",
      "I602",
      "I607",
      "I208",
      "I202",
      "I207",
      "I201"
    ],
    "Duration": "3",
    "Capacity": 80,
    "Group": "201",
    "assigned_classroom": "L204",
    "assigned_time": [24, 56]
  },
  {
    "Subject": "Mobile Applications Programming (1) F",
    "Type": "P",
    "Level": "2",
    "for": ["MO_2f"],
    "Lecturer": "Hazem Awni Shehadeh Rikhawi",
    "Classroom": [
      "I101",
      "I107",
      "I102",
      "I602",
      "I607",
      "I208",
      "I202",
      "I207",
      "I201"
    ],
    "Duration": "3",
    "Capacity": 80,
    "Group": "201",
    "assigned_classroom": "L204",
    "assigned_time": [24, 56]
  },
  {
    "Subject": "Mobile Applications Programming (1) F",
    "Type": "P",
    "Level": "2",
    "for": ["MO_2f"],
    "Lecturer": "Hazem Awni Shehadeh Rikhawi",
    "Classroom": [
      "I101",
      "I107",
      "I102",
      "I602",
      "I607",
      "I208",
      "I202",
      "I207",
      "I201"
    ],
    "Duration": "3",
    "Capacity": 80,
    "Group": "201",
    "assigned_classroom": "L204",
    "assigned_time": [24, 56]
  },
  {
    "Subject": "Mobile Applications Programming (1) F",
    "Type": "P",
    "Level": "2",
    "for": ["MO_2f"],
    "Lecturer": "Hazem Awni Shehadeh Rikhawi",
    "Classroom": [
      "I101",
      "I107",
      "I102",
      "I602",
      "I607",
      "I208",
      "I202",
      "I207",
      "I201"
    ],
    "Duration": "3",
    "Capacity": 80,
    "Group": "201",
    "assigned_classroom": "L204",
    "assigned_time": [24, 56]
  },
  {
    "Subject": "Mobile Applications Programming (1) F",
    "Type": "P",
    "Level": "2",
    "for": ["MO_2f"],
    "Lecturer": "Hazem Awni Shehadeh Rikhawi",
    "Classroom": [
      "I101",
      "I107",
      "I102",
      "I602",
      "I607",
      "I208",
      "I202",
      "I207",
      "I201"
    ],
    "Duration": "3",
    "Capacity": 80,
    "Group": "201",
    "assigned_classroom": "L204",
    "assigned_time": [24, 56]
  },
  {
    "Subject": "Mobile Applications Programming (1) F",
    "Type": "P",
    "Level": "2",
    "for": ["MO_2f"],
    "Lecturer": "Hazem Awni Shehadeh Rikhawi",
    "Classroom": [
      "I101",
      "I107",
      "I102",
      "I602",
      "I607",
      "I208",
      "I202",
      "I207",
      "I201"
    ],
    "Duration": "3",
    "Capacity": 80,
    "Group": "201",
    "assigned_classroom": "L204",
    "assigned_time": [24, 56]
  },
  {
    "Subject": "Mobile Applications Programming (1) F",
    "Type": "P",
    "Level": "2",
    "for": ["MO_2f"],
    "Lecturer": "Hazem Awni Shehadeh Rikhawi",
    "Classroom": [
      "I101",
      "I107",
      "I102",
      "I602",
      "I607",
      "I208",
      "I202",
      "I207",
      "I201"
    ],
    "Duration": "3",
    "Capacity": 80,
    "Group": "201",
    "assigned_classroom": "L204",
    "assigned_time": [24, 56]
  },
  {
    "Subject": "Mobile Applications Programming (1) F",
    "Type": "P",
    "Level": "2",
    "for": ["MO_2f"],
    "Lecturer": "Hazem Awni Shehadeh Rikhawi",
    "Classroom": [
      "I101",
      "I107",
      "I102",
      "I602",
      "I607",
      "I208",
      "I202",
      "I207",
      "I201"
    ],
    "Duration": "3",
    "Capacity": 80,
    "Group": "201",
    "assigned_classroom": "L204",
    "assigned_time": [24, 56]
  },
  {
    "Subject": "Mobile Applications Programming (1) F",
    "Type": "P",
    "Level": "2",
    "for": ["MO_2f"],
    "Lecturer": "Hazem Awni Shehadeh Rikhawi",
    "Classroom": [
      "I101",
      "I107",
      "I102",
      "I602",
      "I607",
      "I208",
      "I202",
      "I207",
      "I201"
    ],
    "Duration": "3",
    "Capacity": 80,
    "Group": "201",
    "assigned_classroom": "L204",
    "assigned_time": [24, 56]
  }
];
